version: '3.8'

services:
  web:
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: mafia_api_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: queen
      MYSQL_ROOT_PASSWORD: queen
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: